#!/bin/sh
BASE=/mnt/usb/H3531/APPS/x11-debian
LOADER="$BASE/lib/ld-linux.so.3"
LIBPATH="$BASE/lib:$BASE/lib/arm-linux-gnueabi:$BASE/lib/arm-linux-gnueabi/lxpanel"
XTERM="$BASE/bin/xterm"
TERMSHELL="$BASE/bin/h3531-terminal-shell"

export LD_LIBRARY_PATH="$LIBPATH"
export DISPLAY=${DISPLAY:-127.0.0.1:0}
export HOME=${HOME:-/var/h3531-lxde}
export TERM=xterm
export SHELL="$TERMSHELL"
export LC_ALL=C

FONT=12x24
GEOMETRY=82x23+120+80
TITLE="H3531 Terminal"
WORKDIR=
COMMAND_STRING=

run_xterm_interactive()
{
    [ -n "$WORKDIR" ] && cd "$WORKDIR"
    exec "$LOADER" --library-path "$LIBPATH" "$XTERM"         -display "$DISPLAY"         -fn "$FONT"         -geometry "$GEOMETRY"         -bg white -fg black         -title "$TITLE"         -xrm '*backarrowKeyIsErase: true'         -xrm '*ttyModes: erase ^?'         -e "$TERMSHELL"
}

run_xterm_argv()
{
    [ -n "$WORKDIR" ] && cd "$WORKDIR"
    exec "$LOADER" --library-path "$LIBPATH" "$XTERM"         -display "$DISPLAY"         -fn "$FONT"         -geometry "$GEOMETRY"         -bg white -fg black         -title "$TITLE"         -xrm '*backarrowKeyIsErase: true'         -xrm '*ttyModes: erase ^?'         -e "$TERMSHELL" -- "$@"
}

run_xterm_string()
{
    [ -n "$WORKDIR" ] && cd "$WORKDIR"
    exec "$LOADER" --library-path "$LIBPATH" "$XTERM"         -display "$DISPLAY"         -fn "$FONT"         -geometry "$GEOMETRY"         -bg white -fg black         -title "$TITLE"         -xrm '*backarrowKeyIsErase: true'         -xrm '*ttyModes: erase ^?'         -e "$TERMSHELL" -- /bin/sh -c "$COMMAND_STRING"
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        -e|--command)
            shift
            [ "$#" -gt 0 ] || exit 64
            run_xterm_argv "$@"
            ;;
        --command=*)
            COMMAND_STRING=${1#--command=}
            shift
            run_xterm_string
            ;;
        --working-directory=*)
            WORKDIR=${1#--working-directory=}
            ;;
        --working-directory)
            shift
            [ "$#" -gt 0 ] || exit 64
            WORKDIR="$1"
            ;;
        --geometry=*)
            GEOMETRY=${1#--geometry=}
            ;;
        --geometry)
            shift
            [ "$#" -gt 0 ] || exit 64
            GEOMETRY="$1"
            ;;
        -t|-T|--title)
            shift
            [ "$#" -gt 0 ] || exit 64
            TITLE="$1"
            ;;
        --title=*)
            TITLE=${1#--title=}
            ;;
        -l|--loginshell|--no-remote)
            # Compatibility options from LXTerminal. The terminal shell helper
            # already creates an interactive shell and xterm is a separate process.
            ;;
        *)
            # Unknown LXTerminal UI-only switches are ignored rather than passed to
            # xterm, because the two programs use different option vocabularies.
            ;;
    esac
    shift
done

run_xterm_interactive
